runtime: nodejs10
env: standard

service: default



handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.next
      static_dir: .next
      secure: always

  - url: /
    secure: always

env_variables:
  NODE_ENV: 'production'