apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
    - image: gcr.io/collab-kube-staging/admin-app
      docker:
        dockerfile: Dockerfile-prod
deploy:
  kubectl:
    manifests:
      - ./kubernetes/*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: collab-kube-staging
