apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: collab-admin-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: collab-admin-ip
spec:
  backend:
    serviceName: collab-admin-nodeport
    servicePort: 3036
---
apiVersion: v1
kind: Service
metadata:
  name: collab-admin-nodeport
spec:
  type: NodePort
  selector:
    app: admin
  ports:
  - port: 3036
    targetPort: 3035
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
spec:
  selector:
    matchLabels:
      app: admin
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin-container
        image: gcr.io/kube-staging-219918/skaffold-example
        ports:
        - containerPort: 3035
        env:
          - name: NODE_ENV
            value: production
